version: '3.3'
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
          - /mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
    client:
        build: ./Client
        ports:
            - '5000:5000'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        image: client_lab
    server:
        build: ./Server
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        image: server_lab